### NumPy Exam
#### This is just a short programming quiz that asks you use a few NumPy features. It is meant to give you a little practice if you don't have NumPy experience.

In [52]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min([input_array])

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / np.max([inputs_minus_min])

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if ((m1.shape[1] != m2.shape[0]) and (m2.shape[1] != m1.shape[0])):
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.dot(m1,m2)
    if m2.shape[1] == m1.shape[0]:
        return np.dot(m2,m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[ 0.     0.375  1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665


# Nice job!  That's right!

## Playground

#### Numpy Array Shape Tests

In [21]:
m1=np.array([[1,2,3],[4,5,6]])
m2=np.array([[1,2,3],[4,5,6]])#np.array([[1],[2],[3],[4]])

In [22]:
#M1 shape?
m1.shape[1]

3

In [23]:
m2.shape[0]

2

In [24]:
if m1.shape[1] != m2.shape[0]:
    print('hrmm')
else:
    print("Yay")

hrmm


In [31]:
np.mean(m1)

3.5

In [41]:
def find_mean(values):
    
    # TODO: Return the average of the values in the given Python list

    np.mean([1,3,4])

    
print("Mean == {}".format(find_mean([1,3,4])))

Mean == None


In [36]:
test_array = np.array([1,3,4])
test_array

array([1, 3, 4])

In [37]:
np.mean(test_array)

2.6666666666666665

Solution

Expected Result:<br>
Input as Array: [[-1  2  7]]<br>
Input minus min: [[0 3 8]]<br>
Input  Array: [[ 0.     0.375  1.   ]]<br>
Multiply 1:<br>
False<br>
Multiply 2:<br>
[[14]<br>
 [32]]<br>
Multiply 3:<br>
[[ 9 12 15]]<br>
Mean == 2.6666666666666665<br>