### Numpy Matrix Operations

Provide the shape of the  matrix.  Our matrix will  `feature` a 2D array containing the input data.

In [29]:
#Original
x = np.array([0.49671415, -0.1382643 ,  0.64768854])
x.shape
x

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [30]:
#Transpose
x.T

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [31]:
#Create a Column Vector
x[:,None]

array([[ 0.49671415],
       [-0.1382643 ],
       [ 0.64768854]])

### Programming quiz
Below, you'll implement a forward pass through a 4x3x2 network, with sigmoid activation functions for both layers.

Things to do:

Calculate the input to the hidden layer.
Calculate the hidden layer output.
Calculate the input to the output layer.
Calculate the output of the network.

## Answer:

In [32]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[ 0.41492192  0.42604313  0.5002434 ]
Output-layer Output:
[ 0.49815196  0.48539772]
